language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test ./...
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
