language: go
sudo: false

go:
  - 1.8.x
  - tip

before_install:
  - go get -t ./...
  - go get github.com/mattn/goveralls

script:
  - PATH="$HOME/gopath/bin:$PATH"
  - script/coverage.sh --coveralls
